### ISSUE TITLE
visual studio 2019 freezes during debug of android app

### ISSUE THREAD

**Issue by grkouk** [viacheslav-lozinskyi/MetaProject#4]
When I try to debug any xamarin forms android application,

 vs 2019 latest version is freezing just before deploying the app to the emulator. When I run the app in local machine UWP version there is no problem. I am attaching a screenshot.
The only solution is to disable metaproject.    ![Annotation 2020-02-17 160307](https://user-images.githubusercontent.com/4976472/74660954-c1207080-519f-11ea-9263-5df88868441c.jpg)

**Comment by viacheslav-lozinskyi** [comment]
Thank you for the information.
I will fix it ASAP.

**Comment by grkouk** [comment]
Waiting for the fix becourse it is a very useful tool.

________________________________

**Comment by viacheslav-lozinskyi** [comment]
I can’t reproduce this bug, but found potential problem which can lead to similar behavior.
It is already fixed. Also this fix improve performance of MetaProject.
New release is already published (Version 1.3.7.1).
Could you write is problem solved?

**Comment by grkouk** [comment]
Sorry to inform you that the problem is not fixed.
I describe again.
Exactly when vs is changing layout to debug and android emulators screen turns white to show the apps screen visual studio freezes. The only way to exit vs is to kill process in task manager. When I kill process then the emulator shows apps screen. This is happening only in android app. Same app in UWP works fine.

I have resharper, vscoloroutput extensions loaded.
I hope I help you to fix the problem.

On 18/2/2020 12:37:04 πμ, Viacheslav Lozinskyi <notifications@github.com> wrote:

I can’t reproduce this bug, but found potential problem which can lead to similar behavior.
It is already fixed. Also this fix improve performance of MetaProject.
New release is already published (Version 1.3.7.1).
Could you write is problem solved?

**Comment by viacheslav-lozinskyi** [comment]
I reproduce this bug.
It appears with with emulator based on "Android 8.1 - API 27".
With "Android 7.1 - API 25" everything works fine.

In any case it is serious problem and I will fix it ASAP.
Thank you for the help.

**Comment by viacheslav-lozinskyi** [comment]
This bug has stable reproduce even with disabled MetaProject.
[Here](https://forums.xamarin.com/discussion/161513/vs2019-android-emulator-hangs-when-debugging-app) is definition and solution of the problem.

MetaProject is not a reason of this freeze.
Could you check this information?

**Comment by grkouk** [comment]
I will check it tomorrow when I am in the office

________________________________

**Comment by viacheslav-lozinskyi** [comment]
Thank you

**Comment by viacheslav-lozinskyi** [comment]
Problem is in my code.
I am working on fixing on it.

**Comment by viacheslav-lozinskyi** [comment]
Fixed version of MetaProject is already released (version 1.3.8.15).
Check it please.

**Comment by grkouk** [comment]
The first impression is that it works fine
I will keep monitoring it and get back to you
Good job

On 24/2/2020 10:46:48 πμ, Viacheslav Lozinskyi <notifications@github.com> wrote:

Fixed version of MetaProject is already released (version 1.3.8.15).
Check it please.

**Comment by viacheslav-lozinskyi** [comment]
Thank you for the found bug.
